### ISSUE TITLE
Is this another ending issue?

### ISSUE THREAD

**Issue by GregTheGrate** [gethryn/doubleL#10]
<p class="calibre2">
Then Eli said cool y, "Leaving already?" </p>

**Comment by GregTheGrate** [comment]
she'l agree to sell the vineyard

**Comment by gethryn** [comment]
Interestingly, `she'l` has only one space after it, so it is failing to match because `she'l agree` means that the search is followed immediately by a letter, not one of our end cases.  Might be a one off.  `coolly` is fixed.

**Comment by gethryn** [comment]
Will close this and track single space issue in #5.

**Comment by GregTheGrate** [comment]
All fixed
