### ISSUE TITLE
Incorrect change

### ISSUE THREAD

**Issue by GregTheGrate** [gethryn/doubleL#11]
coloniall ---- is correct in the original file

<p class="calibre2">
I climbed down from the truck and walked up the fieldstone path to the winery. The rambling ivy-covered brick building was largely my mother's design. She'd sketched dozens of pictures of ideas until she finally settled on one that harmonized the romantic neoclassical architecture she'd grown up with  in  France  with  the  simpler  coloniall style  of  Highland  House  designed  by  Leland's  pragmatic  Scottish  ancestors.  The  result  looked  more  like  a graceful old villa than a commercial structure, which was exactly what she wanted--and what we'd named it. </p>

**Comment by GregTheGrate** [comment]
Running the second time, after I added more words, coloniall is changed in two different places, but the above one is now correct....

**Comment by GregTheGrate** [comment]
There is an instance in the book where colonial has not been changed

**Comment by GregTheGrate** [comment]
emotionall----emotional not in list, is correct in original file

<p class="calibre2">
"Eli's  an  asshole,"  she  said,  "whose  emotionall sensibilities  seem  to  have  atrophied  since  he  married  the  Queen  Bee.  He's  become  so materialistic he thinks the world is full of people just like him." </p>

**Comment by GregTheGrate** [comment]
financiall ---- is correct in orginal

"And  some  hit  man  took  him  out."  Eli  looked  at  me  curiously.  "That's  a  hell  of  a  theory  for  you,  Luce.  You,  ah,  wouldn't  be  in  financiall trouble yourself, would you?" </p>

**Comment by GregTheGrate** [comment]
medievall ---- not in list, correct in original book
 <p class="calibre2">
I still had nightmares about the midsummer's evening we'd left the casino—he'd won, for a change—when two men wearing ski masks forced us off the  Route  de  la  Moyenne  Corniche  near  the  medievall mountaintop  village  of  Eze.  The  view  of  the  Mediterranean  was  spectacular  from  that  height, especially at sunset. I wasn't the only one who appreciated it. One of the men held a gun to Philippe's head and told him in vulgar terms that he would be seeing the water from a much closer vantage point unless he handed over all his money. </p>

**Comment by GregTheGrate** [comment]
Naationall -----not in list, correct in original

 <p class="calibre2">
"Looks  like  we're  not  going  to  get  a  break  from  the  heat  any  time  soon,"  he  said.  "The  Nationall Weather  Service  is  predicting  more  hot,  dry weather for the next few days." </p>

**Comment by GregTheGrate** [comment]
normall ---- not in list, correct in original

 <p class="calibre2">
The  silence  on  the  other  end  of  the  phone  lengthened  beyond  the  boundaries  of  a  normall conversation  as  though  the  line  had  gone  dead.  It happened  from  time  to  time  especially  on  internationall calls,  so  that  on  more  than  one  occasion  I'd  ended  up  chattering  into  the  flat  blackness  of  a severed connection. </p>

**Comment by GregTheGrate** [comment]
There are other instances which I have not documented

**Comment by GregTheGrate** [comment]
Alcoholland ----- holland is in the list :>) but there is no space before hol and.  

<p class="calibre2">
I closed the medicine cabinet and stared at my haunted reflection in his mirror. Alcoholland antidepressants. The worst combination in the world. </p>

**Comment by gethryn** [comment]
Other changes seem to have fixed all of these.

**Comment by GregTheGrate** [comment]
Tested, all working
