### ISSUE TITLE
Single quote start

### ISSUE THREAD

**Issue by GregTheGrate** [gethryn/doubleL#13]
'We'l  knock you----We'll is in the list.  Three spaces after the We'l

 <p class="calibre2">"Yeah,  I  suppose  we  could  get  ahead  of  the  curve  and  advertise  it  ourselves.  How  about  this?  'We'l   knock  you  dead  at  Montgomery  Estate Vineyard. Try our full-bodied Merlot.'"</p>

**Comment by gethryn** [comment]
2540 instances total

**Comment by GregTheGrate** [comment]
Thank you
