### ISSUE TITLE
Think double quotes as an end isn't a goer

### ISSUE THREAD

**Issue by GregTheGrate** [gethryn/doubleL#4]
mythicall"elixir of life"-

**Comment by gethryn** [comment]
not sure why this is matching... it doesn't satisfy the conditions, and the current end characters don't include a double quote: 
```perl
my $before = " —–…“\"-";
my $after = " ,.—–…'’;:?!-";
```

**Comment by gethryn** [comment]
I think moving the hyphen #6 fixed it.
