### ISSUE TITLE
Perhaps - at end isn't working

### ISSUE THREAD

**Issue by GregTheGrate** [gethryn/doubleL#6]
the stil -open kitchen

**Comment by GregTheGrate** [comment]
al -American

**Comment by GregTheGrate** [comment]
unsupervised hel -raising,

**Comment by GregTheGrate** [comment]
crowding  in  to  our  brick-wal ed   ----and the beginning

**Comment by gethryn** [comment]
I have moved the hyphen to the end of the list as perl looks at [a-z] as all characters from A to Z, and not A, -, and Z. although there was no alpha in the search, it's apparently best to put the hyphen at the end.  Have done this.  see if it works.

**Comment by gethryn** [comment]
Seems to have fixed it.

**Comment by GregTheGrate** [comment]
brick-wal ed is still not working....ie    -wal ed

**Comment by gethryn** [comment]
`walled` is not in the list of words to correct. Will add it.

**Comment by GregTheGrate** [comment]
all working
